server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
            strategy: RETAIN_UNIQUE

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  observations:
    key-values:
      application: "+{spring.application.name}"
  tracing:
    sampling:
      probability: 1.0

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

security:
  jwt:
    secret: ${JWT_SECRET:fitverse-default-jwt-secret-key-that-is-long-enough-please-change}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: INFO

resilience4j:
  timelimiter:
    instances:
      default:
        timeout-duration: 3s
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
    instances:
      auth-service:
        base-config: default
      user-profile-service:
        base-config: default
      foodvision-service:
        base-config: default
      calorie-tracker-service:
        base-config: default
      fitness-recommendation-service:
        base-config: default
      chatbot-service:
        base-config: default
      notification-service:
        base-config: default
      analytics-service:
        base-config: default
