CREATE TABLE IF NOT EXISTS profiles (
    user_id BIGINT NOT NULL PRIMARY KEY,
    height_cm DECIMAL(5,2),
    weight_kg DECIMAL(5,2),
    age INT,
    gender VARCHAR(20) NOT NULL DEFAULT 'UNSPECIFIED',
    goal VARCHAR(255),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
